### ISSUE TITLE
Vertex Color Error - Unity

### ISSUE THREAD

**Issue by psparikh** [unity3d-jp/AlembicImporter#48] opened 2018-01-26 22:24 UTC
Using the latest Alembic Importer, I am trying to use an animated Alembic file that has RGBA values stored at every vertex. They are being read in Maya (by recreating color sets), but not Unity. Is it possible to access the vertex color data? Or, could you recommend a direction to make it work? Thanks!

**Comment by psparikh** [comment] 2018-01-27 00:27
Alembic file: https://drive.google.com/file/d/1rYr5etzwgfTyBfja8oRsukPfcuEdoQe8/view?usp=sharing

**Comment by i-saint** [comment] 2018-01-27 04:26
thanks for valuable data. this plugin doesn't support vertex color for now. I will add it.

Alembic's PolyMesh schema doesn't support vertex color. that's why this plugin doesn't support it. but Maya seems can export it as extension attributes.

**Comment by psparikh** [comment] 2018-01-27 06:44
Thank you so much - we have a big team trying to use vertex color and it would be a huge help to add it as soon as possible. How might I access the extension attributes in Unity? Would it be separate from this importer? Thank you again.

**Comment by i-saint** [comment] 2018-01-27 07:00
it require plugin update. without enough knowledge about C++ and Almebic API, it will be difficult.
I think I can release updated plugin in about 10 days.

**Comment by psparikh** [comment] 2018-01-27 07:03
That would be amazing work! Thank you very much. Please write to me if you need any more details about our work and needs.

**Comment by psparikh** [comment] 2018-01-30 20:49
Hi - I'm not sure if I need to make a different issue. But, I am getting an error with the animation in this file. (It only appears for one frame). Any ideas? It works perfectly in Maya 2018. File: https://drive.google.com/file/d/1SOhE5qnTw4duAOInejKhq4_Pt2H0fG54/view?usp=sharing

Thank you!!

**Comment by i-saint** [comment] 2018-01-30 22:03
I confirmed it's a same problem with https://github.com/unity3d-jp/AlembicImporter/issues/46. already fixed in develop version.
vertex color is also working on develop version. I need to test little more...
![alembic_vertexcolor](https://user-images.githubusercontent.com/1488611/35593919-c9b212fa-0654-11e8-9993-7efcafade46f.png)

**Comment by psparikh** [comment] 2018-01-30 22:07
Amazing!! Thank you so much.

**Comment by i-saint** [comment] 2018-01-31 23:50
hi. I'm nearly ready to release new package. but, the change in this this release is quite huge. I want you to test this pre-relase package if you can. (some options are added, some others are removed, but the usage is same) I really appreciate your help.

https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

**Comment by i-saint** [comment] 2018-02-01 00:31
you may encounter this issue #50 (in short: delete AlembicMaterial.cs)

**Comment by psparikh** [comment] 2018-02-01 01:24
The colors look great and the transparencies are showing up. This may just be a bug, but the Alembic Stream Player is not playing the animation when I add the animation as part of the 'Animator' component. When I try to use it using the 'Animation' component, I've received the error "The AnimationClip 'lowpolly_Clip' used by the Animation component 'lowpolly' must be marked as Legacy."

The animations do work if I use it as part of the Timeline editor.

I am continuing my testing today and tomorrow. 
Is it okay if I give you my full notes in about 24 hours?

**Comment by i-saint** [comment] 2018-02-01 01:36
of course. it will be great help. I will try to solve Animator issue..

**Comment by psparikh** [comment] 2018-02-01 02:04
Another issue - High transparencies (lower Alpha values) are not showing up. Can you check this on your end? What shader are you using?

Original Photo:
![capture00001](https://user-images.githubusercontent.com/8129470/35657357-e763799a-06b0-11e8-9663-c0a3dabc482c.png)

Unity Screenshot:
<img width="820" alt="capture" src="https://user-images.githubusercontent.com/8129470/35657367-f30a91de-06b0-11e8-8123-1a5570e10257.PNG">

**Comment by i-saint** [comment] 2018-02-01 02:17
hmm, I think it is a shader's (or at least outside of AlembicImporter's) issue. I'm using my own debug shader ("Overlay.mat" in the package. it can visualize vertex color or other vertex attributes)

I'm going to sleep for a while..

**Comment by i-saint** [comment] 2018-02-01 07:30
I just updated package. Animation issue was fixed.
https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

**Comment by psparikh** [comment] 2018-02-01 07:43
Thanks - will sleep and get back to you tomorrow

**Comment by i-saint** [comment] 2018-02-01 12:18
package updated again. fixed crash bug when there are multiple alembic prefabs in the scene..
https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

**Comment by psparikh** [comment] 2018-02-01 19:10
I am still hitting the Animation/Animator issue.
<img width="1385" alt="capture" src="https://user-images.githubusercontent.com/8129470/35697431-0f272e3e-073f-11e8-99b7-3defe82b35bf.PNG">

Additionally, I've noticed that a lot of settings of my Alembic imports revert to their original setting if I restart Unity. For example, the importer automatically adds a material "Standard" to the models; however, I can't find a way to permanently change that material, besides creating a separate prefab. Additionally, if I want my Animation Clip associated with the Alembic to loop, it unchecks itself upon restart.

If possible, could you add an 'Alpha' or 'Transparency' tab to your Overlay material? I'd love to know whether it's being read perfectly. I like how you had the visualizations for UVs, tangents, and normals.

Thank you for all the help - will continue to write any issues if need be.

**Comment by psparikh** [comment] 2018-02-01 22:33
Update: wrote a shader that got the transparencies to work, so don't worry about the Alpha tab!

**Comment by i-saint** [comment] 2018-02-02 02:30
Animation is working at least on my machine. probably you need to reimport Alembic objects?
and certainly imported assets will be reverted when a project is opened or reloaded.  FBX prefabs have same behavior but Alembic prefabs are more confusing as it seem not read only.  I will add workaround for it.. 
![screenshot 2018-02-02 11 18 34](https://user-images.githubusercontent.com/1488611/35713484-e7842798-080a-11e8-947c-fe888a462866.png)

**Comment by i-saint** [comment] 2018-02-02 09:18
I just realized what you meant about Animation. certainly animation "clip" was broken.

**Comment by i-saint** [comment] 2018-02-02 09:46
fixed animation clip. and I figured it out how to make assets read only. package updated.
 https://github.com/unity3d-jp/AlembicImporter/releases/download/20180201/AlembicForUnity.unitypackage

**Comment by psparikh** [comment] 2018-02-02 21:42
Animations work well! The clips also work. Thank you so much! I don't have any other immediate issues - I'll let you know if I ever hit them.

Thanks again!

**Comment by i-saint** [comment] 2018-02-03 15:37
glad to hear your problem solved :)
I close this issue (milestone reached!), but feel free to update here or add new issue.

**Closed by i-saint** 2018-02-03 15:37 UTC

**Comment by i-saint** [comment] 2018-02-05 11:35
https://github.com/unity3d-jp/AlembicImporter/releases/tag/20180205

**Comment by vutran000** [comment] 2018-03-15 20:01
Hi,

I am developing on a Mac and am using the latest release of this importer.
I see that you used the Overlay.mat material to show the vertex colors, but that material only shows pink on my machine.

Can you tell me what are the proper steps to take to show color? Is there another material/shader I should be using instead?

Thanks

**Comment by i-saint** [comment] 2018-03-16 14:48
@vutran000 simply assigning Overlay.mat should work (I confirmed it works on my Mac). probably there is a problem that is specific on your machine.
if you need more help, send me your project that can reproduce the issue and Editor.log (https://docs.unity3d.com/Manual/LogFiles.html)

**Comment by vutran000** [comment] 2018-03-16 17:07
A unity package of my project and the editor log should be attached.
It does appear there is an issue with the Overlay.mat and my machine. The shader claims it is "not supported on this GPU".

OS:  macOS Sierra 10.12.6
Unity:  2017.3.1f1
Alembic:  20180222

Thanks again
[vutran000_Alembic_Project.zip](https://github.com/unity3d-jp/AlembicImporter/files/1820155/vutran000_Alembic_Project.zip)

**Comment by i-saint** [comment] 2018-03-16 18:37
Editor.log says Graphics API is OpenGL. switching it to Metal solve the problem.
or change "#pragma target 4.5" in Overlay.shader to "#pragma target 3.0" also solve the problem. (I will include this change in future releases)

**Comment by vutran000** [comment] 2018-03-16 21:14
Thank you very much for looking into this. Both of your solutions definitely got Overlay.shader to compile correctly, but I am still not able to get my alembic gameobject to show vertex color.

When I set the shader's attribute to "Colors", it just gives me white. The "Normals" attribute does show color, but it is not the correct vertex color.

Also not sure if this is related or not, but the alembic geometry does not animate when I build for MacOS. However, it does whenever I build the exact same scene for Windows.

**Comment by i-saint** [comment] 2018-03-16 21:36
> When I set the shader's attribute to "Colors", it just gives me white.

I'm 99% sure the problem is .abc file, not shader or material.
ask me only when you are sure the problem is in this plugin. and attach the data that can reproduce the issue when you ask. you are wasting my time.

**Comment by vutran000** [comment] 2018-03-16 21:50
Yes sir. Thanks again for all your help.

**Comment by vutran000** [comment] 2018-03-21 21:03
Hi,

I dug around a little more and found my problem.

In the <AlembicImporter/Plugin/abci/Importer/aiPolyMesh.cpp> file, on line 275. It appears to only read in the colors if the colorset is named "rgba". By default, Maya will name the exported colorset as "colorSet1".

I renamed my colorset in Maya to "rgba" and the colors showed up correctly in Unity.

I have attached two abc files. They are exactly the same, except for their colorset names. You should be able to reproduce the issue by applying the shader to both.

Thanks,

[maya_abc_files.zip](https://github.com/unity3d-jp/AlembicImporter/files/1835185/maya_abc_files.zip)
