### ISSUE TITLE
Bug with tangents?

### ISSUE THREAD

**Issue by dariopixmo** [unity3d-jp/AlembicImporter#5] opened 2016-09-30 20:35 UTC
When I turn Tangents Mode to 'Smooth', some triangles of the imported Alembic meshes turn black when using a normal & height map.

Setting Tangents Mode to 'Split' also has the same problem - the meshes only look correct if the type is set to 'None' or when I remove the normal / height map from the material. Seems some tangents are just set to zero..

![tangents](https://cloud.githubusercontent.com/assets/22551374/19006084/2e863e12-875e-11e6-8efc-b9176d32d4d1.jpg)

Edit: I am using Unity 5.3.4f1 on Windows 10.

Edit2: After having done some further research, it seems that some of the tangents are indeed set to 0 (actually (0,0,0,-1) or (0,0,0,1)). I tried recalculating all tangents manually for each frame and that fixed the issue, but that is obviously not an ideal solution :)

**Comment by dariopixmo** [comment] 2016-11-17 18:29
Hey there, I just wanted to check if there is any news regarding this issue? The importer otherwise is really great, and I would gladly help testing if that would help..

**Comment by madani1991** [comment] 2016-12-06 14:09
Hi, dariopixmo,  I have the same issue and I am in a deadline trying to render my project out. Since it seems that it is not solved yet, Can you explain how you recalculate all tangents manually for each frame? it would be really appreciated! :)

**Comment by dariopixmo** [comment] 2016-12-06 23:50
Hey there, sure thing! I'm not at my work machine atm to double check, but I'm pretty sure I've used the code from this post (#29) on the Unity forums: [](https://forum.unity3d.com/threads/how-to-calculate-mesh-tangents.38984/#post-1043631)
It's not terribly fast (took more CPU time than the alembic stream itself), but it does the trick. Good luck with your project!

**Comment by madani1991** [comment] 2016-12-07 02:57
Thanks A lot, It is so much better now, Although it is giving me some jittering on dynamic object. Hope this can be fixed in an ideal way! :)

**Comment by i-saint** [comment] 2018-01-22 08:09
I will reopen this if I get reproducible data.

**Closed by i-saint** 2018-01-22 08:09 UTC
